name: Lint Terminologie

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  lint-terms:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Scan forbidden terms
        run: |
          set -e
          echo "Scanning for forbidden terms per docs/GLOSSARY.md"
          forbid='investisseur|Investisseur|investisseurs|Investisseurs|abonné premium|crédits|boutique|\bshop\b|fournisseurs|actifs|Revenus mensuels|Paiement mensuel|paiement annuel|Next\.js 1[0-4]|TanStack Start'
          # Ensure base ref is available for diff
          if [ -n "${GITHUB_BASE_REF:-}" ]; then
            git fetch origin "$GITHUB_BASE_REF":"refs/remotes/origin/$GITHUB_BASE_REF" || true
          fi
          base_ref="${GITHUB_BASE_REF:-origin/${{ github.event.pull_request.base.ref }}}"
          if git diff --name-only "$base_ref...HEAD" | xargs -r rg -n --pcre2 "$forbid"; then
            echo "Forbidden terms detected. Please align with docs/GLOSSARY.md" >&2
            exit 1
          else
            echo "OK: no forbidden terms"
          fi
